# Generated by Django 4.2 on 2023-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_role',
            field=models.CharField(choices=[('flutter', 'Flutter'), ('python', 'Python'), ('ui_ux', 'UI/UX'), ('web_development', 'Web Development'), ('devops', 'DevOps'), ('marketing', 'Marketing')], default='flutter', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
