# Generated by Django 4.2 on 2023-04-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_assigned_to_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(blank=True, to='tasks.student'),
        ),
    ]
